### ISSUE TITLE
Null Pointer Exception while executing the scala pragrams

### ISSUE THREAD

**Issue by thugliffe** [dataArtisans/flink-streaming-demo#1]
I get a null pointer exception while executing the sample code from the examples folder. The error is as :

```
Exception in thread "main" java.lang.NullPointerException
    at org.apache.flink.runtime.minicluster.FlinkMiniCluster.startWebServer(FlinkMiniCluster.scala:295)
    at org.apache.flink.runtime.minicluster.FlinkMiniCluster.start(FlinkMiniCluster.scala:268)
    at org.apache.flink.runtime.minicluster.FlinkMiniCluster.start(FlinkMiniCluster.scala:226)
    at org.apache.flink.streaming.api.environment.LocalStreamEnvironment.execute(LocalStreamEnvironment.java:101)
    at com.dataartisans.flink_demo.examples.TotalArrivalCount$.main(TotalArrivalCount.scala:96)
    at com.dataartisans.flink_demo.examples.TotalArrivalCount.main(TotalArrivalCount.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Process finished with exit code 130
```

Am I missing something ??

**Comment by fhueske** [comment]
Thanks for reporting this issue.
The examples assume that the project root folder is set as working directory when the programs are executed (the `./data/dummyLogFile.txt` as specified in `DemoStreamEnvironment` must be found). 
You can set the working directory in Intellij's "Run/Debug Configurations".

Please let me know if that works for you.

**Comment by thugliffe** [comment]
I did what you said but it is still giving me the same null pointer exception.  The val webServer is resolving to null.

**Comment by fhueske** [comment]
So, the path `<workingDir>/data/dummyLogFile.txt` points to this [file](https://github.com/dataArtisans/flink-streaming-demo/blob/master/data/dummyLogFile.txt)?

**Comment by thugliffe** [comment]
yes.

**Comment by StephanEwen** [comment]
.You can also disable the local web frontend in this class:
https://github.com/dataArtisans/flink-streaming-demo/blob/master/src/main/scala/com/dataartisans/flink_demo/utils/DemoStreamEnvironment.scala

The current master does not have that issue any more, so you could also set
the Flink dependency of the example to 1.0-SNAPSHOT.

**Comment by thugliffe** [comment]
I found the cause for the exception. It was due to the default port 8081 being used by some other service. I changed the default port number in the file DemoStreamEnvironment.scala by adding the following code segment and it worked like a charm. 

```
config.setInteger(ConfigConstants.JOB_MANAGER_WEB_PORT_KEY,9999)
```

Thanks for your help.

**Comment by HungUnicorn** [comment]
Had the same issue and the above solution solved the issue
