### ISSUE TITLE
Issue Running the Example code

### ISSUE THREAD

**Issue by FrankRojas** [dataArtisans/flink-streaming-demo#4]
Hello,
Apologies if this is a very basic question, I am having an issue running your code EarlyArrivalCount; I followed all the steps but when I try running the code, I get the following error message (in Linux and in Windows). Please note that when I set
  val writeToElasticsearch = false, it runs and echoes data in the console.
Looks like it's complaining about elasticsearch, I've confirmed that it is running, I also had to make the change recommended in one of the posting:
  config.setInteger(ConfigConstants.JOB_MANAGER_WEB_PORT_KEY,9999)
Any help, advice will be greatly appreciated, Thanks in advance.
Frank

Error Message
log4j:WARN No appenders could be found for logger (org.apache.flink.api.java.typeutils.TypeExtractor).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
05/09/2016 10:37:23 Job execution switched to status RUNNING.
05/09/2016 10:37:23 Source: Custom Source(1/1) switched to SCHEDULED 
05/09/2016 10:37:23 Source: Custom Source(1/1) switched to DEPLOYING 
05/09/2016 10:37:23 Filter -> Filter -> Map(1/1) switched to SCHEDULED 
05/09/2016 10:37:23 Filter -> Filter -> Map(1/1) switched to DEPLOYING 
05/09/2016 10:37:23 TriggerWindow(SlidingTimeWindows(900000, 300000), com.dataartisans.flink_demo.examples.EarlyArrivalCount$EarlyCountTrigger@1f1c7bf6, WindowApply at apply(WindowedStream.scala:209)) -> Map -> (Sink: Unnamed, Sink: Unnamed)(1/1) switched to SCHEDULED 
05/09/2016 10:37:23 TriggerWindow(SlidingTimeWindows(900000, 300000), com.dataartisans.flink_demo.examples.EarlyArrivalCount$EarlyCountTrigger@1f1c7bf6, WindowApply at apply(WindowedStream.scala:209)) -> Map -> (Sink: Unnamed, Sink: Unnamed)(1/1) switched to DEPLOYING 
05/09/2016 10:37:23 Source: Custom Source(1/1) switched to RUNNING 
05/09/2016 10:37:23 TriggerWindow(SlidingTimeWindows(900000, 300000), com.dataartisans.flink_demo.examples.EarlyArrivalCount$EarlyCountTrigger@1f1c7bf6, WindowApply at apply(WindowedStream.scala:209)) -> Map -> (Sink: Unnamed, Sink: Unnamed)(1/1) switched to RUNNING 
05/09/2016 10:37:23 Filter -> Filter -> Map(1/1) switched to RUNNING 
(49551,1356998700000,GeoPoint(-73.97789764404297,40.75187683105469),2)
05/09/2016 10:37:31 TriggerWindow(SlidingTimeWindows(900000, 300000), com.dataartisans.flink_demo.examples.EarlyArrivalCount$EarlyCountTrigger@1f1c7bf6, WindowApply at apply(WindowedStream.scala:209)) -> Map -> (Sink: Unnamed, Sink: Unnamed)(1/1) switched to FAILED 
java.lang.RuntimeException: Could not forward element to next operator
    at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:319)
    at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:300)
    at org.apache.flink.streaming.runtime.io.CollectorWrapper.collect(CollectorWrapper.java:48)
    at org.apache.flink.streaming.runtime.io.CollectorWrapper.collect(CollectorWrapper.java:29)
    at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:51)
    at com.dataartisans.flink_demo.examples.EarlyArrivalCount$$anonfun$5.apply(EarlyArrivalCount.scala:96)
    at com.dataartisans.flink_demo.examples.EarlyArrivalCount$$anonfun$5.apply(EarlyArrivalCount.scala:95)
    at org.apache.flink.streaming.api.scala.WindowedStream$$anon$3.apply(WindowedStream.scala:206)
    at org.apache.flink.streaming.runtime.operators.windowing.WindowOperator.emitWindow(WindowOperator.java:302)
    at org.apache.flink.streaming.runtime.operators.windowing.WindowOperator.processTriggerResult(WindowOperator.java:335)
    at org.apache.flink.streaming.runtime.operators.windowing.WindowOperator.processWatermark(WindowOperator.java:362)
    at org.apache.flink.streaming.runtime.io.StreamInputProcessor.processInput(StreamInputProcessor.java:156)
    at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask.run(OneInputStreamTask.java:63)
    at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:218)
    at org.apache.flink.runtime.taskmanager.Task.run(Task.java:584)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Could not forward element to next operator
    at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:319)
    at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:300)
    at org.apache.flink.streaming.runtime.io.CollectorWrapper.collect(CollectorWrapper.java:48)
    at org.apache.flink.streaming.runtime.io.CollectorWrapper.collect(CollectorWrapper.java:29)
    at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:37)
    at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:316)
    ... 15 more
Caused by: org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
    at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:305)
    at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:200)
    at org.elasticsearch.client.transport.support.InternalTransportClient.execute(InternalTransportClient.java:106)
    at org.elasticsearch.client.transport.support.InternalTransportClient.execute(InternalTransportClient.java:97)
    at org.elasticsearch.client.support.AbstractClient.update(AbstractClient.java:122)
    at org.elasticsearch.client.transport.TransportClient.update(TransportClient.java:345)
    at com.dataartisans.flink_demo.sinks.ElasticsearchUpsertSink.invoke(ElasticsearchUpsertSink.scala:80)
    at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:37)
    at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:316)
    ... 20 more

05/09/2016 10:37:31 Job execution switched to status FAILING.
05/09/2016 10:37:31 Source: Custom Source(1/1) switched to CANCELING 
05/09/2016 10:37:31 Filter -> Filter -> Map(1/1) switched to CANCELING 
05/09/2016 10:37:31 Filter -> Filter -> Map(1/1) switched to CANCELED 
05/09/2016 10:37:31 Source: Custom Source(1/1) switched to CANCELED 
05/09/2016 10:37:31 Job execution switched to status FAILED.

**Comment by fhueske** [comment]
Hi @FrankRojas, which version of Elasticsearch are you running? The example is based on Elasticsearch 1.7.3, so not the most recent version.

**Comment by FrankRojas** [comment]
Thank you Fabian, that was it; I switched to the correct version of Elasticsearch and it started working.
Thank you for sharing your knowledge.
Frank
